### ISSUE TITLE
Backspace key sends [DEL](127) instead of [BACKSPACE](8)

### ISSUE THREAD

**Issue by kalsifer-742** [npat-efault/picocom#145]
I'm writing a serial CLI for stm32.
While debugging the code i noticed the thing i stated in the title.
I tried to do the same thing with minicom and the correct code was being sent.
I think there might be some bug in picocom.
Let me know if i can provide some needed informations.
Thank you.

**Comment by hanlof** [comment]
There is an option in minicom (under 'Screen and keyboard') that lets you define what BS should send so DEL is most likely what your BS key actually produces. You can test this in your shell by hitting Ctrl-V followed by BS and then it will print ^? if it's DEL and ^H otherwise.

**Comment by kalsifer-742** [comment]
Hello, thank you for answering!
Is it possible to configure what picocom is sending when pressing Backspace? Like with minicom ?

**Comment by wsakernel** [comment]
Check the "INPUT, OUTPUT, AND ECHO MAPPING" section in the manpage.
