### ISSUE TITLE
Open picocom inside cygwin from NTemacs term

### ISSUE THREAD

**Issue by technician77** [npat-efault/picocom#35]
I'm running 64bit cygwin and compiled/installed picocom. Picocom works from bash flawlessly. Now I'm trying to use a term inside a native 64bit NTEmacs. When I do I get "FATAL: failed to add I/O device: Filedes is not a tty". Any idea what is happening there? I know it's more like an emacs problem but I'm hoping you might be able to point me in the right direction based on the error message. The term access to any interactive source is notoriously problematic under Windows but I hope to get it running anyway. Currently I'm falling back to plink.

**Comment by npat-efault** [comment]
Hi,

The error you 're seeing comes from this check in the picocom source:

    https://github.com/npat-efault/picocom/blob/master/term.c#L455

Obviously the "isatty" function returns zero (false) when run from
within you NTEmacs terminal. I don't know why. How *exactly* do you
start picocom from within NTEmacs? Inside my Emacs (on Linux) with
"M-x term" picocom works fine.

A thing you could possibly try, if all else fails, is to remove the
check above (term.c:L455) and recompile. No guarantee it will work (as
things may fail later-on), but you could try anyway.

/npat

**Comment by technician77** [comment]
I start it using function below. I'm not a coder, so I hope nothing is severly wrong. Versions of function below work for ssh, telnet and plink. Original also not by me. I'll try the recompile.

(defun quick-serial-picocom (baud port)
  "Connect to a remote host by Serial."
  (interactive "sPort (default /dev/ttyS11 equals COM12): \nsBaud (default 9600): ")
  (let* ((port (if (equal port "") "/dev/ttyS11" port))
        (baud (if (equal baud "") "9600" baud))
        (switches (list "-b" baud port)))
        (set-buffer (apply 'make-term "serial" "picocom" nil switches))
        (term-mode)
        (term-char-mode)
        (term-set-escape-char ?\C-a)
        (switch-to-buffer "*serial*")))

**Comment by technician77** [comment]
When I remove that if statement in term.c I get problems with the baud option. I get error below although value 9600 was given. After recompiling the unedited version it reverts back to the error above.

Process serial exited abnormally with code 1
Invalid --baud: 0
                 Run with '--help'.

**Comment by npat-efault** [comment]
A function like the one above works fine in my Emacs (on linux).

Please try recompiling picocom (without the isatty() test on
term.c:L455) and tell me if it works.

/npat

**Comment by npat-efault** [comment]
This error (Invalid --baud: 0) has nothing to do with picocom. It's an
emacs-lisp related problem. Try replacing the function definition
line:

    (defun quick-serial-picocom (baud port)

 with:

    (defun quick-serial-picocom (port baud)

It should work (again with the isatty() check in term.c:L455 removed)

**Comment by npat-efault** [comment]
> When I remove that if statement in term.c I get error below now:
> FATAL: failed to add I/O device: Cannot get the device attributes: Inappropriate ioctl for device

Then, I guess, the terminal inside NTEmacs does *not* behave like a terminal at all (does not support termios).

Picocom is not *normally* made to work on such a terminal. 

As a last resort, you could remove the checks whether the terminal-setup function calls fail in lines picocom.c:L1560 and picocom.c:L1565 (do nothing if r < 0).

**Comment by technician77** [comment]
Removed code below. Lines were 1547 and 1553. You seemed to be refering to a different picocom.c than the latest release version. Removal of code resulted in success, although I'm not sure about the side-effects.

> Then, I guess, the terminal inside NTEmacs does not behave like a terminal at all (does not support termios).
This sounds like my NTEmacs. Well all terminals (term, ansi-term,shell) inside it seem to be quite broken but they can be used for some limited purposes. Mabe someone will fix the code someday.

`	if ( r < 0 )
		fatal("failed to add I/O device: %s", 
			  term_strerror(term_errno, errno));
	term_set_raw(STI);
	r = term_apply(STI, 0);
	if ( r < 0 )
		fatal("failed to set I/O device to raw mode: %s",
			  term_strerror(term_errno, errno));`

**Comment by npat-efault** [comment]
> Removed code below. Lines were 1547 and 1553. You seemed to be refering to a different picocom.c 
> than the latest release version

Yes I was refering to picocom tip. For the latest release (2.1) these are the respective lines. 

Glad it worked for you...

**Comment by m4l490n** [comment]
I'm experiencing something similar to this problem but the solution here does not work. I'm working on an embedded linux board with an iMX6.

I'm getting **FATAL: failed to add I/O device: Filedes is not a tty** when _trying to run picocom from an init script_.

Then if I remove the code:

`    if ( r < 0 )
        fatal("failed to add I/O device: %s",
              term_strerror(term_errno, errno));
    term_set_raw(STI);
    r = term_apply(STI, 0);
    if ( r < 0 )
        fatal("failed to set I/O device to raw mode: %s",
              term_strerror(term_errno, errno));
`
I get the error **FATAL: stdin closed**

If I run picocom from the command line having logged into the board then it works fine with and without the mentioned code.

**Comment by pospospos2007** [comment]
I got the error too when I was trying to run the  picocom on the Ubuntu background. Anyone could help I would appreciate!

`1605675182] FATAL: failed to add I/O device: Filedes is not a tty 
[1605675183] picocom v2.2
[1605675183] 
[1605675183] port is        : /dev/ttyUSB0
[1605675183] flowcontrol    : none
[1605675183] baudrate is    : 9600
[1605675183] parity is      : none
[1605675183] databits are   : 8
[1605675183] stopbits are   : 1
[1605675183] escape is      : C-a
[1605675183] local echo is  : no
[1605675183] noinit is      : no
[1605675183] noreset is     : no
[1605675183] nolock is      : no
[1605675183] send_cmd is    : sz -vv
[1605675183] receive_cmd is : rz -vv -E
[1605675183] imap is        : 
[1605675183] omap is        : 
[1605675183] emap is        : crcrlf,delbs,
[1605675183]`
