### ISSUE TITLE
If I use `--echo` option, do I need to run `stty echo` on the serial device?

### ISSUE THREAD

**Issue by CMCDragonkai** [npat-efault/picocom#36]
Basically if the `stty -a` reports `-echo`, do I need to first run `stty echo` before `picocom --echo` will work? Or does `picocom` take care of setting the tty flags?

Also this question applies to the parity mode too.

**Comment by npat-efault** [comment]
Picocom takes care of setting the tty flags itself.

Regarding the --echo picocom option, specifically, picocom handles local-echo internally.

So normally, you should not need to do stty to set any tty flags. Picocom does this as required (for baudrate, parity, echo and all).

**Comment by CMCDragonkai** [comment]
Ok thanks, would be great if this was on the README.md
