### ISSUE TITLE
No fresh picocom in Ubuntu

### ISSUE THREAD

**Issue by CKD4XXH** [npat-efault/picocom#43]
Ubuntu repositories lacks a fresh picocom. Why?

$  sudo apt-get dist-upgrade
...

$  picocom --help
picocom v1.7

**Comment by npat-efault** [comment]
I don't know. I guess nobody made a package.

**Comment by npat-efault** [comment]
I think it would be better to ask this question to the Ubuntu (or other distro) package maintainers...
