### ISSUE TITLE
Straying non-opt command line parameter were silently ignored

### ISSUE THREAD

**Issue by Joe-Merten** [npat-efault/picocom#52]
E.g. when typing:
`$ picocom /dev/ttyUSB0 TRALALA BANANA`
picocom starts up same as just
`$ picocom /dev/ttyUSB0`

So when I just forgot the `-b` switch like this:
`$ picocom /dev/ttyUSB0 115200`
picocom starts with standard baudrate of 9600 without a command line parameter warning.

**Comment by npat-efault** [comment]
Yep It's a bug. I will fix it.
