### ISSUE TITLE
port name is limited to 127 chars

### ISSUE THREAD

**Issue by Joe-Merten** [npat-efault/picocom#54]
When a longer port name is specified, it's truncated to 127 chars.

Of course, this is really rare case, but  I'd run into this issue when using `/dev/serial/` serial symlinks in Linux (Kubuntu).

I have to work with a device having a quite long device name, which finally evaluates to something like:

    /dev/serial/by-id/usb-Biothentic_II_smartcard_reader_with_fingerprint_sensor._CDCACM_USB_To_RS-232_Emulation_Device_B9E871A4-F213-4DD1-997C-403F073EF126-if00

My current ugly workaround:

- wrote a bash script around the picocom call
- following the symlink to e.g. /dev/ttyACM0
- then passing /dev/ttyACM0 to picocom

I could provide a PR for this issue (replacing `strncpy()` by `strdup()` like doing for the log filename).

**Comment by npat-efault** [comment]
Yes it's a known limitation, but since it can *practically* occur *and* it can be easily fixed, please submit the PR.
