### ISSUE TITLE
Custom baud rate in OSX won't work

### ISSUE THREAD

**Issue by JoeMerten** [npat-efault/picocom#57]
I'd recently added custom baud rate support for OSX, but after some more testing, I found out that it not work as expected. I'd tested with:
- OSX El Capitan 10.11.6
- Ftdi and Prolific adapters

In most cases, the desired custom baud rate will just be substituted by on of the standard baud rates.

I'll investigate it deeper now and hopefully provide a fix soon.

**Comment by Joe-Merten** [comment]
Some deeper analysis:
`cfsetospeed()` seems to store the desired baud rate (e.g. 12345) correctly into `termios` struct (checked by calling `cfgetospeed()` before `tcsetattr()` called.
But when then calling `term_apply()`, `tcsetattr()` fail with: "Invalid argument".
For my opinion, I have to call `ioctl(fd, IOSSIOSPEED, &speed)` after `tcsetattr()` called.

**Comment by npat-efault** [comment]
Yes, this could be a solution... See also my comments in PR #59. You must also find a solution for getting  tcgetattr() to work with custom baud rates (i.e. a way to read-back the custom baud rate set).

**Comment by npat-efault** [comment]
Also if the high-baud constants for OSX, the ones >= 460800 do not work *without* the custom ioctls, they should be removed...

**Comment by Joe-Merten** [comment]
Reading back custom baud rate via `tcgetattr()` already works with PR #59. The logic is:
- `tcsetattr()` applies the termios data to the fd (with faked B9600)
- `ioctl(fd, IOSSIOSPEED, &speed)` now applies the real desired baud rate (e.g. 12345) to the fd
- the following `tcgetattr()` then puts the 12345 into the termios struct
- and following `cfgetospeed()` calls are returning the right custom baud rate

I'd tested this using Ctrl+A+V command.

**Comment by Joe-Merten** [comment]
Constants: 460800 and 921600 are working without special handing in OSX, so those both can resist.
But e.g. 500k, 1M (and all above) do not, so I'll remove them - or put em into `custbaud_osx.h` to have them available for Ctrl+A+U/D in case of custom baudrate enabled.

**Comment by npat-efault** [comment]
I would suggest removing them all if custom baud is not enabled. That is: Without custom-baud support, stay with the baudrates defined by the OS.
