### ISSUE TITLE
Whitespace

### ISSUE THREAD

**Issue by npat-efault** [npat-efault/picocom#60]
Whitespace in code is a bit of a mess (though *not* formatting, formatting is fine). At some places spaces are used, and TABs are used elsewhere. Also trailing whitespace is present at several lines. 

It should be fixed.

- Make all files use only spaces
- Remove trailing spaces
- Edit `.editorconfig` to make `indent_style = space`

Changes should not affect code formatting.

**Comment by Joe-Merten** [comment]
fixed by PR #61
