### ISSUE TITLE
argument for command

### ISSUE THREAD

**Issue by arpitjindal97** [npat-efault/picocom#64]
Add one argument which will accept the command to execute and then exit the program

**Comment by Wesley-Chan** [comment]
$ your_cmd && picocom /dev/ttyS0

Is this what you want?

**Comment by arpitjindal97** [comment]
I meant this something like this 
`picocom /dev/ttyS0 -send AT`

It will open the port send the string `AT` print the output and exit.

**Comment by Wesley-Chan** [comment]
Like this?

    $ echo "AT" > /dev/ttyS0

**Comment by JoeMerten** [comment]
If I understand right, then you want to:
- Start picocom with opening serial port.
- Send some data through serial port (like provided with PR #65).
- After that, wait some specific time for incoming data (which could be captured via `--logfile` option).
- And finally terminate picocom after have received that data (or timeout).

If so, than I think that picocom is not the right tool. For my opinion, picocom is made for interactive human to machine communication and not for some job automation.

You might take a look on [Pulog.py](https://github.com/JoeMerten/Jfe/blob/master/Framework/tools/Pulog.py). I think you just need to add something like an `--initstring` option.
