### ISSUE TITLE
Add "to hex" character mappings

### ISSUE THREAD

**Issue by npat-efault** [npat-efault/picocom#75]
Consider adding the following character mappings:

- **spchex**: Map all "special" characters (< 0x20 || 0x7f) to their hexadecimal values, something like this: `[17]`. Exclude CR and LF (leave them as is)
- **crhex**: Map CR to its hex value (`[13]`)
- **lfhex**: Map LF to its hex value (`[10]`)
- **8bithex**: Map all bytes with the 8th  bit set to their hex value
- **nrmhex**: Map "normal" characters (0x20 <= c < 0x7f ) to their hexadecimal values.

(If more than one mappings apply for a char, then use a predefined mappings precedence order to decide which to apply. Eg: `crlf, crhex` or `crhex, crlf` will both map CR -> LF)

**Comment by adam-stamand** [comment]
Sorry to being this back from the dead, but wouldn't it make sense to have a 'allhex' option so that you can easily get a hexdump of all received characters? I understand you can use several mappings, but I'm not sure you get full coverage with just these mappings.
