### ISSUE TITLE
Add custom baudrate support for BSD (at least FreeBSD)

### ISSUE THREAD

**Issue by JoeMerten** [npat-efault/picocom#77]
As commented in #62 on 2016-12-19, adding custom baudrate support should not be a big thing, as it behaves very similar to macOS.

I'd checked it out custom baudrates last year with FreeBsd (native FreeBsd 11 installation).

Regarding `cf[sg]et[io]speed()` it behaves similar to macOS. Every baudrate can directly passed as its integer value and this works.
In contrast to macOS we don't need to workaround in `tcsetattr()`; FreeBsd is more clean and straight forward in this point.
So the approach to support custom baudrates for FreeBsd will be:
- rename `custbaud_osx.[hc]` to `custbaud_bsd.[hc]` (this is still correct, as macOS / OSX started as a descendant of BSD)
- adding `#ifdef __FreeBSD__`; I'll don't add `__OpenBSD__` etc now, as I currently don't have test environment for it
- adding `__APPLE__` around the macOS specific `tcsetattr()` replacement code

**Comment by npat-efault** [comment]
Agreed. If you can make the changes and test them, please submit a PR.

**Comment by JoeMerten** [comment]
Finally tested on:
- FreeBSD 11 on Acer Notebook
- OSX El Capitan 10.11.6 on Macbook Pro
- Kubuntu 16.04.3 64 Bit on Macbook Pro
- all with Ftdi usb serial adapters
