### ISSUE TITLE
Add warning in case of desired uart port settings were not correctly applied

### ISSUE THREAD

**Issue by JoeMerten** [npat-efault/picocom#78]
Tested with picocom v3.1a on Linux (Kubuntu 16.04, 64 bit) with Ftdi usb/uart adapter.

Invoking something like:

    picocom /dev/ttyUSB0 --baud 12345678

let picocom start normaly and printing it's welcome stuff with something like:

    port is        : /dev/ttyUSB0
    flowcontrol    : none
    baudrate is    : 12345678
    parity is      : none
    databits are   : 8
    ....

but when checking the settings by pressing `Ctrl+A V` I see, that my desired baudrate has not been applied:

    *** baud: 12345678 (9600)
    *** flow: none
    *** parity: none
    *** databits: 8
    ...

It would be nice to have a warning on startup like e.g.:

    WARNING: Desired baudrate is 12345678 but applied baudrate is 9600; this might depend upon your OS and/or hardware limitations.

The same is for the other uart settings like flow control, parity, databits et cetera.

Tested the same (baudrate) on macOS, picocom terminates (as expected) with something like "FATAL: failed to config port …".

**Comment by npat-efault** [comment]
This is how it's supposed to behave. 

In the Linux case, the O/S did *not* report an error. The system call to configure the port succeeded. So picocom cannot report an error or warning. If one wants to see what the actual vs the requested settings are, he can do so with C-a, C-v, exactly as described in the manual. If there is a discrepancy, both values will be shown (again, as documented in the manual).

In the macOS case, the O/S *did* report an error on the system call to configure the port. So picocom reports the error.

**Comment by JoeMerten** [comment]
#83 should solve this.
In my default setup (Kubuntu 16.04 Linux & Ftdi serial adapter) I got for example:

    ./picocom /dev/ttyUSB0 -b 12345678 -d 6
    picocom v3.1a
    port is        : /dev/ttyUSB0
    flowcontrol    : none
    baudrate is    : 12345678
    parity is      : none
    databits are   : 6
    stopbits are   : 1
    ...
    *** WARNING: One or more port configuration settings were not applied as desired:
    *** baud: 12345678 (9600)
    *** databits: 6 (5)
    *** This might depend upon your OS and/or hardware limitations.

    Type [C-a] [C-h] to see available commands
    Terminal ready

**Comment by npat-efault** [comment]
Too verbose on startup. I don't like it. 

I would compromise on this:

Make show_status() count mismatches. 

Add a "quiet" flag to show_status(). If set do not print anything (only count mismatches).

On startup call show_status (quietly) to count mismatches. If any, show a single-line warning like this:

    !! Settings mismatch !! Use [C-v] command to see actual settings

The warning should appear only if the --quiet command-line option is not given. 

Optionally add a couple of lines in the manpage (section about displaying settings)

**Comment by npat-efault** [comment]
Also: the test (for mismatches) should happen only if --noinit is not given.

**Comment by JoeMerten** [comment]
Ok, respecting `--quiet` and `--noinit` is commited and also manpage update.

Regarding your suggested message, I not sure if I should print `[C-a] [C-v]` or just `[C-v]`.

When printing just `[C-v]`, the output is like:

    !! Settings mismatch !! Use [C-v] command to see actual settings
    Type [C-a] [C-h] to see available commands
    Terminal ready

And this might confuse a new user on how to use the escape key, isn't it?

**Comment by JoeMerten** [comment]
Have committed output with just `[C-v]` for the first, but I'll change it you change your mind.

Would like to keep those `mode` parameter `0/1/2` in `show_status()` to easily change to automatic output of related mismatches in code. This might be sensible if running picocom with `--no-escape` were you cannot type `[C-v]`.

**Comment by npat-efault** [comment]
Perhaps it should say: 

    !! Settings mismatch !! Type [C-a] [C-v] to see actual port settings

I definitely don't like `show_status()` as it currently is. Way too convoluted with all the modes and the if's all over the place. I would simply add a mismatch count (as you have), and a `quiet` argument. Then I would replace the fd_printf()'s with a marco that checks quiet and does nothing (prints nothing) if set. This way it will be much easier to follow.

**Comment by JoeMerten** [comment]
Refactored `show_status()` now as you suggested by using an appropriate macro. It's much better readable code now, IMHO even better readable than before my changes.

Still supporting `mode` = `0/1/2`, hoping it's now ok for you after this refactoring. But if you still dislike, I'll gave up and change it into your suggested `quiet` = `0/1`.

**Comment by JoeMerten** [comment]
Btw: With the recent commit, I'd introduced:

    const char *downup_str[] = {
        [0] = "down",
        [1] = "up",
    };

to stop repeat that `rts_up ? "up" : "down"` within the code.
It's off topic from this PR, but I think it should also be used in `do_command()` for `KEY_TOG_DTR` and `KEY_TOG_RTS`.

**Comment by npat-efault** [comment]
Added the check and warning with minimal changes to the code.  I don't want to make to much of a fuss about it. 

Maybe, sometime in the future, if a need arises we can then refactor show_status() more thoroughly. But for now it's ok. 

If you can, pls,  run it a couple of times to see if it works for you .

**Comment by JoeMerten** [comment]
Hmm, I'd tested my refactored code with all possible combinations for config matches / mismatches and found the code quite cleaner than before. But however, it is as it is. Of course, I'll test your changes.

Btw: You'd also discarded my manpage additions which you have requested. Don't know it this was intended or not.

**Comment by npat-efault** [comment]
No it wasn't. I'll ad them.

**Comment by npat-efault** [comment]
manpage updated and re-generated
