### ISSUE TITLE
compiler warning reg. printf format on 32 bit target

### ISSUE THREAD

**Issue by JoeMerten** [npat-efault/picocom#85]
In `picocom.c`, `parse_args()`:

    printf("initstring len : %ld bytes\n", strlen(opts.initstring));

This will definitively result in wrong printf output!

The format code `%ld` won't match to `size_t` type returned by `strlen()`.
Could either change the format code to `%z` but this will fail for older compilers.

Alternatively, change format code to `%lu` and also cast the `strlen()` to `unsigned long` like:

    printf("initstring len : %lu bytes\n", (unsigned long)strlen(opts.initstring));

**Comment by npat-efault** [comment]
Good catch, thanks
