### ISSUE TITLE
We may need a --raise-rts command line options

### ISSUE THREAD

**Issue by npat-efault** [npat-efault/picocom#86]
On most systems, the DTR as well as the RTS modem control lines are raised (asserted) when the serial port is opened. The user can pass the `--lower-dtr` and / or `--lower-rts` command line options to override this (i.e. to lower---reset---the respective line immediately after the port is configured).

On some systems, though, the RTS line remains low when the port is opened. Because of this, a `--raise-rts` command-line option may be useful, that asserts the RTS line immediately after opening and configuring the port. This way the user has control of the state of both modem-control lines after picocom starts.

**Notice:** All systems (AFAIK) raise the DTR line when the port is opened, so there is no need for an explicit `--raise-dtr` option.

**Comment by JoeMerten** [comment]
I'll add this if you want, after finished the bsd stuff.

**Comment by npat-efault** [comment]
Yes, sure.

**Comment by JoeMerten** [comment]
Along my testing with several Bsd variants, I found out that at least FreeBsd 11.0 don't raise rts nor dtr upon open port. Both handshake lines left untouched upon open, staying in the state which there were before open port.

**Comment by npat-efault** [comment]
Highly unlike! Modems do not connect with DTR kept low (low DTR means "hangup"). You need to investigate more. Maybe it's an artefact of the emulation, or something else? Googling around I have found references that DTR is raised when the first process opens the port, and lowered when the last process closes it... We could also add a --raise-dtr option, mostly  for symmetry...

**Comment by npat-efault** [comment]
Also, BSD has `tty` devices, `cua` devices, as well as `tty.init` and `cua.init`, and the respective `.lock` devices. Maybe (just maybe) you need to disable -clocal on the `init` device, in order for the modem Ctrl lines to be assertwd, or some other similar dance... I don't know...

**Comment by npat-efault** [comment]
What happens if you explicitly raise the DTR line after opening the port (using `C-t`)? Does it work?

**Comment by npat-efault** [comment]
Thinking about it, I tend to lean towards adding a `--raise-dtr` option, as well, so that the user can explicitly dictate the state of both mctrl lines on startup, regardless of the peculiarities of each system. Worst-case it will be superfluous and useless for most systems, but will do no harm...

**Comment by JoeMerten** [comment]
> Maybe it's an artefact of the emulation.

For FreeBsd, I'd tested using a native installation, not only VM. And even tested with Ftdi and Prolific adapters got the same results. But have only tested with `/dev/ttyU0`, not `cua`, `.init` nor `.lock`. 

> What happens if you explicitly raise the DTR line after opening the port (using `C-t`)? Does it work?

Yes, this works after changed `port.c` changed to use `#define USE_IOCTL` for FreeBsd.

Finally, I also think that `--raise.dtr` will do no harm and we should add it for symmetry.

Btw: Have to do some other work for the next some days, but I'll come back soon.
