### ISSUE TITLE
Issue release 3.1 by end of Jan 2018

### ISSUE THREAD

**Issue by npat-efault** [npat-efault/picocom#89]
A lot of small fixes, small improvements, and a few new features have collected since the major 3.0 release. We should issue a minor 3.1 release to capture these.

By the end of Jan 2018 seems like a good time...

**Comment by JoeMerten** [comment]
Thank you for that excellent and handy tool which I use in my daily work. Also thx for the productive teamwork.

**Comment by npat-efault** [comment]
[Release 3.1](https://github.com/npat-efault/picocom/releases) has been issued. Download and enjoy...
